src/backend/shortener/urls.py
from django.urls import path

from .views import IndexView, RedirectionView, InfoView

app_name = 'shortener'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<slug:slug>/info', InfoView.as_view(), name='info'),
    path('<slug:slug>', RedirectionView.as_view(), name='redirection'),
]

src/backend/urlphobia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortener.urls')),
]

src/backend/shortener/models.py
from random import sample

from django.db import models
from django.shortcuts import reverse


class URL(models.Model):
    slug = models.SlugField(max_length=10, unique=True, db_index=True)
    destination = models.URLField()

    def save(self, *args, **kwargs):
        while True:
            try:
                self.slug = SlugGeneratorService.get_slug_suggestion()
            except Exception as e:
                print(e)
            else:
                break

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("shortener:info", kwargs={"slug": self.slug})

    def __str__(self):
        return f"{self.slug} --> {self.destination}"


class SlugGeneratorService:
    symbols = ('QWERTYUIOPASDFGHJKLZXCVBNM'
               'qwertyuiopasdfghjklzxcvbnm'
               '1234567890-_')
    length = 7

    @classmethod
    def get_slug_suggestion(cls):
        """ Generate random slug for URL model """
        return ''.join(sample(cls.symbols, cls.length))

src/backend/shortener/forms.py
from django import forms

from .models import URL


class URLForm(forms.ModelForm):
    class Meta:
        model = URL
        fields = ('destination', )

src/backend/shortener/views.py
from django.views.generic import CreateView, RedirectView, DetailView

from .models import URL
from .services import IndexService, RedirectionService, InfoService
from .forms import URLForm


class IndexView(CreateView):
    template_name = 'index.html'
    template_name_suffix = ''
    form_class = URLForm

    index_service = IndexService()

    def form_valid(self, form: URLForm):
        return self.index_service.handle_form_valid(
            form) or super().form_valid(form)


class InfoView(DetailView):
    model = URL
    template_name = 'info.html'
    context_object_name = 'url'

    # An `InfoService` instance is used in `get_context_data`, but line below
    # is commented out because instance is being created only in one place and
    # with using `self.object`

    # info_service: InfoService

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return InfoService(self.object).modify_context(context)


class RedirectionView(RedirectView):
    redirection_service = RedirectionService()

    def get_redirect_url(self, *args, **kwargs):
        return self.redirection_service.get_redirect_url(*args, **kwargs)

src/backend/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>URL Phobia</title>
</head>

<body>
  <h1>Paste your URL below</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Shorten</button>
  </form>
</body>

</html>

src/backend/templates/info.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <h1>
    thanks!
  </h1>
  <div>
    Short url: {{ short }}
  </div>
  <div>
    Destination: {{ destination_trunc }}
  </div>
  <a href="{% url 'shortener:index' %}">
    <button>Go To Main Page</button>
  </a>
  <a href="{{ url.destination }}">
    <button>Go To Destination URL</button>
  </a>
</body>

</html>